### PR TITLE
chore: bump ij gradle to 1.9.0 (#614)

### LINKED ISSUE #614: bump Gradle IntelliJ Plugin to 1.9.0

### PR DESCRIPTION
**Pull request by lstocchi**
it resolves #614

### CODE REVIEW

**Comment by adietish** [comment]
I can reproduce the error that happens in Github actions:
```
> Task :buildSearchableOptions FAILED
2022-10-12 18:07:54,077 [    178]  ERROR - oncurrency.BoundedTaskExecutor - Resource not found: /idea/nullApplicationInfo.xml
java.lang.RuntimeException: Resource not found: /idea/nullApplicationInfo.xml
```
The intellij gradle plugin is the culprit. It works for me when I use version `1.7.0`. It fails when I use `1.8.1` or `1.9.0`.

**Comment by adietish** [comment]
this might be related to https://github.com/JetBrains/gradle-intellij-plugin/issues/1099

**Comment by lstocchi** [comment]
@adietish i don't think it's the same. The issue here also looks different from the one you faced in Ij k8s. Damn MacOs... in my case it's like the system property is not set correctly.
By doing the thing below i overcome the error
```
buildSearchableOptions {
    if (System.getProperty("idea.platform.prefix") == null) {
        systemProperties["idea.platform.prefix"] = ''
    }
}
```

**Comment by lstocchi** [comment]
Closing it as 1.9.0 is not enough for 2022.3. The terminal doesn't work. It needs to be bumped to 1.10

**Pull request closed without merging**
