### PR TITLE
fix: remove border that does not overlap to combobox (#361)

### LINKED ISSUE #361: Install buttons in Tekton Hub dialog are not good looking when selected
**Steps:**
1. EXEC: select "ClusterTask", pick "Import from TektonHub" in ctx menu
2. ASSERT: list of available tasks in Tekton hub are listed
3. EXEC: select an item and look at the "install"-button

**Result:**
image
The button has rounded corners but an angular border around it. Between the 2 the background shines through. In my eyes this is not good looking.

### PR DESCRIPTION
**Pull request by lstocchi**
it fixes #361 and https://github.com/redhat-developer/intellij-tekton/issues/358

@adietish I changed how the buttons are created and now it is the same as in vscode. I don't use the combo anymore. Does it look better on your Mac? Is it easier to use?

hub

This is how it looks in vscode
image

### CODE REVIEW

**Review by adietish — APPROVED** [review]
Much of an improvement to me, thus +1
Commented in https://github.com/redhat-developer/intellij-tekton/issues/361#issuecomment-857519424 and https://github.com/redhat-developer/intellij-tekton/issues/358#issuecomment-857535084 on why I consider this to be much better than what we had before. GJ!

ps. jetbrains design guide suggests to use a split button in those situations (or alternatively drop the option alltogether like @jeffmaury pointed out): https://jetbrains.design/intellij/controls/split_button/
Your buttons comes close to it and improves things.

**Comment by lstocchi** [comment]
> ps. jetbrains design guide suggests to use a split button in those situations (or alternatively drop the option alltogether like @jeffmaury pointed out): https://jetbrains.design/intellij/controls/split_button/
> Your buttons comes close to it and improves things.

:scream: I didn't know of that split button. I'm going to use it then. The experience will be the same but atleast i'm going to clean the code a bit. Thanks for the tip!!

**Comment by adietish** [comment]
nice, now fully IJ design guide compliant: 
image
+1

**Review by adietish — APPROVED** [review]
nice, now fully IJ design guide compliant: 
image
+1

ps. in my case hitting the button "Install as ClusterTask" takes ~5 seconds until the "Save to cluster" dialog shows up. I initially thought that my click wasn't noticed and thus started clicking on other buttons. But this delay might be my machine that's under heavy load of a minikube with plenty of pods running (knative & tekton extensions installed). A later enhancement could be to provide some visual feedback that the button was pressed. ex. turn the mouse pointer to a hour glass, disable the button or a progress bar etc. ?

**Comment by lstocchi** [comment]
> ps. in my case hitting the button "Install as ClusterTask" takes ~5 seconds until the "Save to cluster" dialog shows up. I initially thought that my click wasn't noticed and thus started clicking on other buttons. But this delay might be my machine that's under heavy load of a minikube with plenty of pods running (knative & tekton extensions installed). A later enhancement could be to provide some visual feedback that the button was pressed. ex. turn the mouse pointer to a hour glass, disable the button or a progress bar etc. ?

Good point :+1:

**Pull request merged**
