### PR TITLE
fix: Add cluster information in telemetry login information

### LINKED ISSUE #416: Add telemetry information for cluster connected to
### Goal
Provide the cluster version information the user connects to through the extension

### Acceptance Criteria
- The extension should send data to telemetry, regarding the connected cluster version.
- This should cover OpenShift and Kubernetes clusters

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #416

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by jeffmaury** [comment]
Requires https://github.com/redhat-developer/intellij-common/pull/78

**Review by lstocchi — APPROVED** [review]
LGTM
The only thing that doesn't fully convince me is the telemetry action name `login`. Maybe `cluster info`?

**Comment by jeffmaury** [comment]
> 
> 
> LGTM
> The only thing that doesn't fully convince me is the telemetry action name `login`. Maybe `cluster info`?

Well the event is login but that data attached to the event is details of the cluster we just logged into

**Comment by lstocchi** [comment]
> Well the event is login but that data attached to the event is details of the cluster we just logged into

Ok, i don't have a strong opinion on this, so it is ok to be merged for me :+1:

**Pull request merged**
