### PR TITLE
fix: use kubernetes-client 5.7.2 to fix fabric8io/kubernetes-client#3189

### PR DESCRIPTION
**Pull request by adietish**
related to https://github.com/redhat-developer/intellij-common/pull/104

### CODE REVIEW

**Comment by adietish** [comment]
I'll put this PR on hold as long as the dependencies (common, kubernetes) are not published in the correct version. It looks as if using dependencies with different kubernetes client versions causes havoc at runtime.

**Comment by lstocchi** [comment]
I can work on it right now but i'm using the plugin from the marketplace and it works for me

**Comment by lstocchi** [comment]
Ah ok, replicated. I didn't update the k8s plugin

**Comment by lstocchi** [comment]
Closing it as https://github.com/redhat-developer/intellij-tekton/pull/474 was merged for fast release

**Pull request closed without merging**
