### PR TITLE
Add "Add Trigger" action

### LINKED ISSUE #210: Add trigger to a pipeline
Add an action to the pipeline context menu to be able to add a trigger a pipeline. Adding a trigger would create the required Tekton resources (EventListener, TriggerTemplate, etc) in order to configure triggers and expose a webhook url that user can add to the Git provider repository settings. Example:
https://github.com/tektoncd/triggers/tree/master/examples/github

User should be able to easily get access to the webhook url associated with the pipeline after triggers are configured.

See https://github.com/redhat-developer/vscode-tekton/issues/347

### PR DESCRIPTION
**Pull request by lstocchi**
it resolves #210 

It took a while but i'm quite satisfied with the workflow now. 

The process is similar to the classic start wizard. The difference is that the `Add Trigger` wizard has an extra step to pick/create triggerbindings.

A user can choose to select one or more existing bindings and/or create a new one.

image

When creating a new binding there are 5 templates to be used. Each template can be edited, and because there is no code completion here, a check is made before to go to the next step. If the configuration is invalid the wizard display some info so user can fix it.

image

If one or more bindings are chosen, you will see the list of all params belonging to the binding inside the parameter step.
As an example if i pick the triggerbinding below 

```
spec:
  params:
    - name: n1
      value: 10
    - name: n2
      value: $(body.pull_request.head.sha)
```

the user will see the img below. 
To be more user-friendly, one can use a variable by typing `$variable`, but before to create the triggerTemplate the plugin will interpolate the variable correctly -> `$(tt.params.variable)`

image

The user can also choose to not select/create any binding and go over. In this case the eventListener will only have the triggerTemplate section.

Last but not least, the `Add Trigger` action is available for both task and pipeline. 

Below a gif

addtrigger

**NOTES for the review:**

There are still some things to improve (added some TODO in the code) but i stopped here so we can release it this week if everything works fine. This PR is ready for review so you can give me a feedback on the UX as the features will not change.

The things you should be aware of

- No tests made, i'm working on them now
- Not sure if texts inside the wizard are written correctly or we can improve it somehow. The thing i'm sure is that i want to add them as i was completely lost when using the `Add Trigger` action in the console the first time. They don't explain what you have to do, which resources you have to select. There is just a mention to `Git Provider Type`. What if I have a binding not related to Git? Then not a word that make me think (tekton noob) they are listing trigger bindings. Quite confusing.
image

- Now i create all resources "manually" but i saw that yesterday there was a new release of the fabric8 tekton client that supports triggers, so i will switch to that next sprint.
- The eventListener is created by using the default `pipeline` serviceAccount but i think we should allow the user to override it.
- Not sure if it works with old version of tekton triggers, which versions should we support?
- There is no way to retrieve the el URL easily, one has to open the el in the editor

I'm ccing @sudhirverma so he can see what we merge and see if he wants to add something to vscode ext.

### CODE REVIEW

**Review by jeffmaury — CHANGES_REQUESTED** [review]
Remarks:
- why the list of existing trigger bindings is displayed in a list and not a combo box it will use less space in the UI
- I don't get why the user next to select the checkbox: we could have the following logic: allow user specified name in the com box and if the name does not exist, then enable the create trigger binding UI elements

Also I tried to create a trigger binding (as I have not trigger bindings on my cluster)

image

And clicking `Next` to does switch to the next page and I found the following stack trace in the IJ log:

```
2020-10-05 09:57:01,681 [ 631973]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2019.2  Build #IC-192.5728.98                                                    
2020-10-05 09:57:01,681 [ 631973]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.3; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o                             
2020-10-05 09:57:01,681 [ 631973]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10                                                                                 
2020-10-05 09:57:01,691 [ 631983]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Tekton Pipelines by Red Hat version: 0.2.0-SNAPSHOT                           
2020-10-05 09:57:01,691 [ 631983]  ERROR - llij.ide.plugins.PluginManager - Last Action: AddTriggerAction                                                                  
2020-10-05 09:57:10,970 [ 641262]  ERROR - llij.ide.plugins.PluginManager - No value present                                                                               
java.util.NoSuchElementException: No value present                                                                                                                         
        at java.base/java.util.Optional.get(Optional.java:148)                                                                                                             
        at com.redhat.devtools.intellij.tektoncd.ui.wizard.addtrigger.AddTriggerWizard.doBeforeNextStep(AddTriggerWizard.java:70)                                          
        at com.redhat.devtools.intellij.tektoncd.ui.wizard.BaseWizard.doNextAction(BaseWizard.java:343)                                                                    
        at com.redhat.devtools.intellij.tektoncd.ui.wizard.BaseWizard.lambda$createSouthPanel$3(BaseWizard.java:299)                                                       
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)                                                                           
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)                                                                       
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)                                                                    
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)                                                                             
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)                                                             
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)                                                                                          
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)                                                                                     
        at java.desktop/java.awt.Component.processEvent(Component.java:6416)                                                                                               
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)                                                                                               
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)                                                                                          
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)                                                                                          
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)                                                                                              
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)                                                                             
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)                                                                              
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)                                                                                  
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)                                                                                          
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)                                                                                                
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)                                                                                              
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)                                                                                         
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)                                                                                                     
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)                                                                                                     
        at java.base/java.security.AccessController.doPrivileged(Native Method)                                                                                            
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)                                               
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)                                               
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)                                                                                                     
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)                                                                                                     
        at java.base/java.security.AccessController.doPrivileged(Native Method)                                                                                            
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)                                               
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)                                                                                             
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:873)                                                                                     
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:818)                                                                                           
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:461)                                                                                   
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:693)                                                         
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:460)                                                                                            
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)                                                                  
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)                                                                     
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)                                                                     
        at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)                                                                                   
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)                                                                                   
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)                                                                                   
        at java.base/java.security.AccessController.doPrivileged(Native Method)                                                                                            
        at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)                                                                                   
        at java.desktop/java.awt.Dialog.show(Dialog.java:1063)                                                                                                             
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:707)                                                                
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:432)                                                                         
        at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1685)                                                                                           
        at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1644)                                                                                             
        at com.redhat.devtools.intellij.tektoncd.actions.AddTriggerAction.lambda$null$2(AddTriggerAction.java:105)                                                         
        at com.redhat.devtools.intellij.common.utils.UIHelper.lambda$executeInUI$0(UIHelper.java:31)                                                                       
        at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)                                                                      
        at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:152)                                                                             
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)                                                                  
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)                                                           
        at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)                                                                    
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)                                                                                  
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)                                                                                         
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)                                                                                                     
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)                                                                                                     
        at java.base/java.security.AccessController.doPrivileged(Native Method)                                                                                            
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)                                               
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)                                                                                             
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:873)                                                                                     
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:822)                                                                                           
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:461)                                                                                   
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)                                                         
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:460)                                                                                            
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)                                                                  
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)                                                                     
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)                                                                  
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)                                                                              
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)                                                                              
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)                                                                                      
2020-10-05 09:57:10,971 [ 641263]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2019.2  Build #IC-192.5728.98                                                    
2020-10-05 09:57:10,971 [ 641263]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.3; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o                             
2020-10-05 09:57:10,971 [ 641263]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10                                                                                 
2020-10-05 09:57:10,972 [ 641264]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Tekton Pipelines by Red Hat version: 0.2.0-SNAPSHOT                           
2020-10-05 09:57:10,972 [ 641264]  ERROR - llij.ide.plugins.PluginManager - Last Action: AddTriggerAction                                                                  
```

**Comment by lstocchi** [comment]
Now the trigger step is like this
image
 and you can add new bindings (more than one if the user wants) and look at the content of those already existing
image

@jeffmaury can you give it a look? WDYT?

**Comment by jeffmaury** [comment]
I was not able to test it because I create the following pipeline:

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-deploy
spec:
  tasks:
  - name: maven
    taskRef:
      kind: ClusterTask
      name: maven
```
 
but I cannot add a Trigger as it states that it has an invalid state as it as no resources !!!!

**Comment by jeffmaury** [comment]
So I decided to add a resource to the pipeline but when add trigger is launched it complains because there is no equivalent existing resource in the cluster (because the model is derived from the run model).
Also I think we should be in par in terms of templates:
- gitlab vs github (we propose push for gitlab and pr for github)
- aligned with openshift (providers cluster trigger bindings for github push pr and pr review comment)

**Review by jeffmaury — CHANGES_REQUESTED** [review]
See comments

**Comment by jeffmaury** [comment]
Remarks:
- when listing the trigger templates it should be good to sort them alphabetically so that we have the github one grouped together, gitlab also and so one
- the first time I move over the Save link it moves a few pixels
- when I select Add trigger I see nothing in the tree ?

**Comment by lstocchi** [comment]
> Remarks:
> 
> * when listing the trigger templates it should be good to sort them alphabetically so that we have the github one grouped together, gitlab also and so on
> * the first time I move over the Save link it moves a few pixels
> * when I select Add trigger I see nothing in the tree ?

1) good point. Fixed it
2) it doesn't happen to me. Is it very annoying? Can be a problem with your screen resolution? Which do you use? So i try to replicate it
3) Yeah, you need to click the refresh action right now as there are no watchers for the triggers. I opened a new issue as the new fabric8 tekton client now supports triggers and we can add them. https://github.com/redhat-developer/intellij-tekton/issues/236

**Review by jeffmaury — APPROVED** [review]
LGTM now

**Pull request merged**
