### PR TITLE
chore: Update schemas to Tekton Pipelines 0.56.0

### PR DESCRIPTION
**Pull request by l-qing**
Ref:
* add cel field
  * https://github.com/tektoncd/pipeline/blob/v0.56.0/pkg/apis/pipeline/v1beta1/when_types.go#L28-L45
* validation:
  * https://github.com/tektoncd/pipeline/blob/v0.56.0/pkg/apis/pipeline/v1beta1/when_validation.go#L49-L79

### CODE REVIEW

**Comment by sbouchet** [comment]
@l-qing : please fix generator and ci

**Comment by l-qing** [comment]
I am a `Golang` programmer, I'm not familiar with `Java`.
I've just dealt with an issue in Golang CI, but I don't understand the Java issues.
I've also tried to run `./gradlew runIde` locally using the [`main`](4122ae32c74704dcc27b73f571f8086d687b2dc4) version, but it didn't work.

I can no longer see the error messages from CI, so I'm not sure how to debug it.

I might need some help, I can't handle the remaining issues alone.

**Comment by sbouchet** [comment]
@l-qing thanks for fixing the go generator for the schema. 
the remaining issues are related to the unit test suite that takes the new schema as input and fails. 
I'll take a look

**Comment by l-qing** [comment]
> @l-qing thanks for fixing the go generator for the schema. the remaining issues are related to the unit test suite that takes the new schema as input and fails. I'll take a look

Thank you very much for your assistance, thanks! 👍

**Comment by sbouchet** [comment]
this will fix https://github.com/redhat-developer/intellij-tekton/security/dependabot/14

**Review by sbouchet — APPROVED** [review]
LGTM

**Pull request merged**
