### PR TITLE
feat: Add hub view (#433)

### LINKED ISSUE #433: Create TektonHub view
We should create a tektonHub view similar to what it is shown in vscode

### PR DESCRIPTION
**Pull request by lstocchi**
it resolves #433 and #438

it needs https://github.com/redhat-developer/intellij-common/pull/90

### CODE REVIEW

**Review by jeffmaury — CHANGES_REQUESTED** [review]

**Comment by jeffmaury** [comment]
I think I already mentioned it but isn't it possible to shrink the layout:

image

As a side remark, I noticed none of the commit messages respect conventional commit so I don't know how this will land in the release notes

**Comment by lstocchi** [comment]
> I think I already mentioned it but isn't it possible to shrink the layout:
> 
> image
> 
> As a side remark, I noticed none of the commit messages respect conventional commit so I don't know how this will land in the release notes

What do you mean by shrinking the layout? I'm able to resize the layout
shrinktektonhub

About commits, by squashing and merging all commits you will only see the PR title `feat: Add hub view` so this is what you will see in the release notes.

**Comment by jeffmaury** [comment]
> 
> 
> > I think I already mentioned it but isn't it possible to shrink the layout:
> > As a side remark, I noticed none of the commit messages respect conventional commit so I don't know how this will land in the release notes
> 
> What do you mean by shrinking the layout? I'm able to resize the layout
> shrinktektonhub
> 
> About commits, by squashing and merging all commits you will only see the PR title `feat: Add hub view` so this is what you will see in the release notes.

I mean there is too much space between the version info and the name of the next task.

**Comment by lstocchi** [comment]
This is how it looks now
image

**Comment by jeffmaury** [comment]
See the selected one:

image

I think we can gain space that is above the task name (but need to check with the Install button)
I also think we can gain space below the version and rating info

**Comment by lstocchi** [comment]
New view
image

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
