### PR TITLE
chore(skip-release): bump sinceIdea to IU-2022.3

### PR DESCRIPTION
**Pull request by adietish**
Caused following change that requires `sinceIdea` to be bumped to `IU-2022.3`
https://github.com/redhat-developer/intellij-common/pull/219

### CODE REVIEW

**Comment by adietish** [comment]
A test is failing with the bump of base IC version:
`GenericCompletionProviderTest`
```java
   public void testTaskCompletionWithoutAnyInput() {
        assertTrue(getSuggestionsForFile("task1.yaml").isEmpty());
    }
```
`getSuggestionsForFile("task1.yaml")` returns a list with "apiVersion" in it while the test asserts that the list is empty.

**Comment by adietish** [comment]
@sbouchet: I think that we should change the assertion in the test to be valid when "apiVersion" is returned because it's a change in the default behaviour of the platform. Agree?

**Comment by adietish** [comment]
@sbouchet: I introduced a switch in the test that fails starting with `IU-2024.1`:
```java
        if (getIDEAVersion() >= 2024.1f) {
            assertOrderedEquals(suggestions, "apiVersion"); // default completion returns 'apiVersion'
        } else {
            assertTrue(suggestions.isEmpty());
        }
```

**Review by sbouchet — APPROVED** [review]
LGTM

**Pull request merged**
