### PR TITLE
fix: avoid prompt to allow editing non-project files (#391)

### LINKED ISSUE #391: Should not be asked to allow "Non-Project Files Protection" when editing resources
**Steps:**
1. EXEC: in tekton tree: select "Tasks" category & pick "New Task" in ctx menu 
2. ASSERT: editor with task template shows up
3. EXEC: start typing in the editor

**Result:**
A dialog "Non_Project Files Protection" pops up, asking you to allow editing non-project files
image

**Expected result:**
Should not be bothered by such a dialog.

### PR DESCRIPTION
**Pull request by adietish**
fixes #391 
depends on https://github.com/redhat-developer/intellij-common/pull/52

### CODE REVIEW

**Review by lstocchi — APPROVED** [review]
Works as always on Linux which is good :+1: 
We could move the editing policy class to commons as it will be used by other plugins as well

**Comment by adietish** [comment]
@lstocchi: moved the extension to commons at https://github.com/redhat-developer/intellij-common/pull/52
What stays in intellij-tekton is using the extension (plugin.xml) and setting the appropriate data to virtual files.

**Comment by adietish** [comment]
@lstocchi [PR for intellij-common](https://github.com/redhat-developer/intellij-common/pull/52) was merged. Dare to test again, please?

**Comment by lstocchi** [comment]
@adietish LGTM. I also made it test to Yevhen on IJ knative (with your fix) https://github.com/redhat-developer/intellij-knative/pull/27 and he said it works perfectly. :partying_face:

**Pull request merged**
