### PR TITLE
fix: enable/disable deploy button in create bundle dialog

### PR DESCRIPTION
**Pull request by lstocchi**
it resolves https://github.com/redhat-developer/intellij-tekton/issues/612

### CODE REVIEW

**Review by jeffmaury — APPROVED** [review]
LGTM but the deploy button is enabled even if the image name is not valid

**Comment by lstocchi** [comment]
> LGTM but the deploy button is enabled even if the image name is not valid

Yeah i made it on purpose so the user can see the error message with the suggestion. Otherwise it is only visible on the tooltip but if you don't pay attention to it and you start typing and you see the button always disabled, you don't get the reason.

**Comment by jeffmaury** [comment]
Yes but seems that on JBT we tried to prevent as much as possible. And I think JetBrains has some kind of recommandations, maybe @adietish may help. Can't you put the error message somewhere else than tooltip ?

**Comment by lstocchi** [comment]
Updated to this
image

**Comment by adietish** [comment]
> Yes but seems that on JBT we tried to prevent as much as possible. And I think JetBrains has some kind of recommandations, maybe @adietish may help. Can't you put the error message somewhere else than tooltip ?


@lstocchi, @jeffmaury: 
> Updated to this image

looks good to me. I'd - like you did - disable "Deploy" when not possible and have an info/warning telling the user about (violated) constraints

**Pull request merged**
