### PR TITLE
Use icons to replace color to report task execution in the graphi…

### LINKED ISSUE #238: Change color to icon in the PipelineRun diagram preview
For accessibility reason we should prefer icons instead of colors to reflect the task execution status

### PR DESCRIPTION
**Pull request by jeffmaury**
…cal editor

Fixes #238

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by lstocchi** [comment]
I think it doesn't work for me. Should i see the icon in the left side, right?
image

**Comment by jeffmaury** [comment]
> 
> 
> I think it doesn't work for me. Should i see the icon in the left side, right?
> image

Yes, let me try on RHEL

**Comment by jeffmaury** [comment]
@lstocchi can you test again now with 2019.3

**Review by lstocchi — APPROVED** [review]
Works fine now 
image

**Pull request merged**
