### PR TITLE
add support for workspaces when using taskRef completion

### LINKED ISSUE #225: Add workspaces field when displaying task by using taskref code completion

### PR DESCRIPTION
**Pull request by lstocchi**
it resolves #225 and #227 

Now the taskRef code completion also shows clusterTasks (if present). To distinguish them from normal tasks i added a label ot the right.

This patch also add support for workspaces.

clustertasktaskref

About tests, I didn't find a way to inject my mocked classes/methods inside the call made by the CodeInsightTestFixture, so making this PR ready for review without tests right now. I'll keep looking at it, sooner or later i will discover the lacking piece.

### CODE REVIEW

**Comment by jeffmaury** [comment]
Tested the code completion on **taskRef.name**:
- worked as I can now see the cluster tasks being listed.
- but the issue I have is that the kind **attribute** was specified to **Task** and is now duplicated, is it fixable ?

**Comment by lstocchi** [comment]
> Tested the code completion on **taskRef.name**:
> 
> * worked as I can now see the cluster tasks being listed.
> * but the issue I have is that the kind **attribute** was specified to **Task** and is now duplicated, is it fixable ?

Yes, i think we can check if the `kind` has already been added before and replace it but not sure if it's worth the effort as it will be uncomplete. This use case happens if you are editing an existing task in a pipeline. What if the old task also had some params/resources/workspaces? Are we going to replace them too? Or only the `kind`?

**Comment by jeffmaury** [comment]
If we are to follow the replace pattern then we must do it for every field. But I think this can be part of another issue.
Can you rebase it so that we can process the release ?

**Comment by lstocchi** [comment]
> If we are to follow the replace pattern then we must do it for every field. But I think this can be part of another issue.
> Can you rebase it so that we can process the release ?

Rebased :+1:

**Review by jeffmaury — APPROVED** [review]

**Pull request merged**
