### PR TITLE
Allow to install tektonhub tasks as clustertasks (#294)

### LINKED ISSUE #294: Install Task from TektonHub as ClusterTask

### PR DESCRIPTION
**Pull request by lstocchi**
it resolves #294

It works exactly as in vscode, the install button has a dropdown option that allow users to install a hub task as clusterTask
image

### CODE REVIEW

**Comment by jeffmaury** [comment]
I was surprised as I expected I could go from ClusterTasks to the Hub dialog but could not 😃

**Comment by jeffmaury** [comment]
The UI is strange to me:
- I think the button should be switched to combo as there is already an arrow
- the Install button on the left side does not have the same option

**Comment by lstocchi** [comment]
> I was surprised as I expected I could go from ClusterTasks to the Hub dialog but could not

I also thought about it but then i didn't know if i had to also change the behavior of the buttons. Like installing the clusterTasks as default if you open the the hub from the ct node.

> The UI is strange to me:

> I think the button should be switched to combo as there is already an arrow

I didn't use the combo bc it could be complicated for the first click. I mean, let's suppose we have a combo (install and install as ct items) and the first item is selected at first. How can you click on `install` when it's already selected? An alternative is to use an empty first item in the combo but i don't like that much. I prefer the user to click.

> the Install button on the left side does not have the same option

Yes i copied how it works in vscode but we can add the feature there as well

**Comment by jeffmaury** [comment]
> 
> 
> > I was surprised as I expected I could go from ClusterTasks to the Hub dialog but could not
> 
> I also thought about it but then i didn't know if i had to also change the behavior of the buttons. Like installing the clusterTasks as default if you open the the hub from the ct node.
> 
> > The UI is strange to me:
> 
> > I think the button should be switched to combo as there is already an arrow
> 
> I didn't use the combo bc it could be complicated for the first click. I mean, let's suppose we have a combo (install and install as ct items) and the first item is selected at first. How can you click on `install` when it's already selected? An alternative is to use an empty first item in the combo but i don't like that much. I prefer the user to click.
I think there are 2 events for the combox:
- the select event when you click on the arrow on the right
- the click event when you click on the rest of the widget 
> 
> > the Install button on the left side does not have the same option
> 
> Yes i copied how it works in vscode but we can add the feature there as well

**Comment by lstocchi** [comment]
@jeffmaury PR updated. The install button is now a combobox. The feature to install a task or as a ct is available in both panel (left column and details). The tektonhub dialog can be opened from clusterTasks node as well.

**Review by jeffmaury — CHANGES_REQUESTED** [review]
I think the default should be Install as ClusterTask when run from the ClusterTasks node.
Also I noticed when I click on a task, I can hear some sound and I found some errors in the log:

```
javax.swing.text.StateInvariantError: GlyphView: Stale view: javax.swing.text.BadLocationException: Length must be positive
	at java.desktop/javax.swing.text.GlyphView.getText(GlyphView.java:138)
	at java.desktop/javax.swing.text.GlyphPainter1.getSpan(GlyphPainter1.java:63)
	at java.desktop/javax.swing.text.GlyphView.getPreferredSpan(GlyphView.java:585)
	at java.desktop/javax.swing.text.FlowView$LogicalView.getPreferredSpan(FlowView.java:757)
	at java.desktop/javax.swing.text.FlowView.calculateMinorAxisRequirements(FlowView.java:241)
	at java.desktop/javax.swing.text.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:710)
	at java.desktop/javax.swing.text.html.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:162)
	at java.desktop/javax.swing.text.BoxView.checkRequests(BoxView.java:936)
	at java.desktop/javax.swing.text.BoxView.getPreferredSpan(BoxView.java:546)
	at java.desktop/javax.swing.text.html.ParagraphView.getPreferredSpan(ParagraphView.java:258)
	at java.desktop/javax.swing.text.html.LineView.getMinimumSpan(LineView.java:74)
	at java.desktop/javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:904)
	at java.desktop/javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
	at java.desktop/javax.swing.text.BoxView.checkRequests(BoxView.java:936)
	at java.desktop/javax.swing.text.BoxView.getMinimumSpan(BoxView.java:569)
	at java.desktop/javax.swing.text.html.BlockView.getMinimumSpan(BlockView.java:378)
	at java.desktop/javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:904)
	at java.desktop/javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
	at java.desktop/javax.swing.text.BoxView.checkRequests(BoxView.java:936)
	at java.desktop/javax.swing.text.BoxView.getMinimumSpan(BoxView.java:569)
	at java.desktop/javax.swing.text.html.BlockView.getMinimumSpan(BlockView.java:378)
	at java.desktop/javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:904)
	at java.desktop/javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
	at java.desktop/javax.swing.text.BoxView.checkRequests(BoxView.java:936)
	at java.desktop/javax.swing.text.BoxView.getPreferredSpan(BoxView.java:546)
	at java.desktop/javax.swing.text.html.BlockView.getPreferredSpan(BlockView.java:362)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.getPreferredSpan(BasicTextUI.java:1447)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:952)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1680)
	at java.desktop/javax.swing.JEditorPane.getPreferredSize(JEditorPane.java:1345)
	at com.intellij.ide.plugins.newui.VerticalLayout.preferredLayoutSize(VerticalLayout.java:60)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1823)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1807)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1682)
	at com.intellij.ui.components.JBScrollPane$Layout.layoutContainer(JBScrollPane.java:466)
	at java.desktop/java.awt.Container.layout(Container.java:1537)
	at java.desktop/java.awt.Container.doLayout(Container.java:1526)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane.validate(DialogWrapperPeerImpl.java:911)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:748)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:746)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:745)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1900)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:687)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:708)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:433)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1698)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1657)
	at com.intellij.openapi.ui.messages.MessageDialog.show(MessageDialog.java:177)
	at com.intellij.ui.messages.MessagesServiceImpl.showMessageDialog(MessagesServiceImpl.java:69)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:290)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:306)
	at com.intellij.openapi.ui.Messages.showYesNoDialog(Messages.java:573)
	at com.intellij.openapi.ui.Messages.showYesNoDialog(Messages.java:592)
	at com.intellij.openapi.ui.Messages.showYesNoDialog(Messages.java:616)
	at com.redhat.devtools.intellij.tektoncd.utils.DeployHelper.lambda$saveOnCluster$0(DeployHelper.java:42)
	at com.redhat.devtools.intellij.common.utils.UIHelper.executeInUI(UIHelper.java:28)
	at com.redhat.devtools.intellij.tektoncd.utils.DeployHelper.saveOnCluster(DeployHelper.java:41)
	at com.redhat.devtools.intellij.tektoncd.ui.hub.HubModel.installHubItem(HubModel.java:171)
	at com.redhat.devtools.intellij.tektoncd.ui.hub.HubMarketplaceTab.installHubItem(HubMarketplaceTab.java:177)
	at com.redhat.devtools.intellij.tektoncd.ui.hub.HubMarketplaceTab.lambda$getInstallCallback$1(HubMarketplaceTab.java:164)
	at com.redhat.devtools.intellij.tektoncd.ui.hub.HubItem$1.mousePressed(HubItem.java:183)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:776)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:687)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:708)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:433)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1698)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1657)
	at com.redhat.devtools.intellij.tektoncd.actions.TektonHubAction.lambda$actionPerformed$3(TektonHubAction.java:58)
	at com.redhat.devtools.intellij.common.utils.UIHelper.lambda$executeInUI$0(UIHelper.java:31)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:154)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by lstocchi** [comment]
@jeffmaury i tried to replicate your exact error but i wasn't able to get that. I found other 3-4 different errors :laughing: while clicking like a crazy on all tasks visible on my screen. I made a fix to avoid to make tens of calls if someone clicks multiple times on multiple items. All the errors i found previously seemed to be disappeared. 

Can you try again and see if this new year took some luck to our side or we need to wait for the 2022? 
If it doesn't work let me know what you do to face that error please.

**Review by jeffmaury — CHANGES_REQUESTED** [review]
That does not work better for me as when I click on an item on the left; the click is effective only 50% of the time. But reading the code, I noticed that you are fetching data asynchronously (so outside the UI thread) but once the data is fetched, the UI is updated in the same thread which is wrong.
So I would suggest:
- revert your last commit (scheduling)
- add `UIHelper.executeInUI` when updating the UI

**Comment by lstocchi** [comment]
> That does not work better for me as when I click on an item on the left; the click is effective only 50% of the time. But reading the code, I noticed that you are fetching data asynchronously (so outside the UI thread) but once the data is fetched, the UI is updated in the same thread which is wrong.
> So I would suggest:
> 
> * revert your last commit (scheduling)
> * add `UIHelper.executeInUI` when updating the UI

I tried that before and it wasn't working. Now i found out the reason. The EDT is blocked when a modal dialog is opened.... now it should work as expected. Give it a try please

**Review by jeffmaury — APPROVED** [review]
Works much better now

**Pull request merged**
