### PR TITLE
feat: add support for optional workspace

### LINKED ISSUE #241: Handle optional workspaces
Tekton Pipelines 0.17.0 introduces the notion of optional workspaces. That will probably impact our start wizard

See #240

### PR DESCRIPTION
**Pull request by lstocchi**
it resolves #241

### CODE REVIEW

**Comment by lstocchi** [comment]
Blocked for the moment, asked if there is a way to bypass questions about empty optional workspaces https://github.com/tektoncd/cli/issues/1444

**Comment by lstocchi** [comment]
https://github.com/tektoncd/cli/pull/1465 has been merged. We can work on it again :crossed_fingers:

**Comment by lstocchi** [comment]
@jeffmaury this patch allows users to start a pipeline/task with an optional workspace. So if a workspace is optional you are not forced to pick it and you can start the pipeline/task normally. If the workspace is not optional is works as before.

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
